name: GitHub Actions Demo with Cypress

run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules
        
  cypress-test-actions:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        
      - name: Run all cypress test
        run: npm run cy:run actions

      - run: echo "ğŸ This job's status is ${{ job.status }}."

  cypress-test-location:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3     
        
      - name: Run all cypress test
        run: npm run cy:run location

      - run: echo "ğŸ This job's status is ${{ job.status }}."
      
  cypress-test-networkRequests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3           
        
      - name: Run all cypress test
        run: npm run cy:run networkRequests

      - run: echo "ğŸ This job's status is ${{ job.status }}."      